CONFIG = {
    # facebook token the voice kid
    'FACEBOOK_TOKEN_GHVN': 'EAAcHG1IN8z4BAE5g7icAZAbINWQsarukGn9xs2opUCzqL9rPQlGOW6iCAp3L61ZBNItPasU7S9kJWH5dgpz7dhjLVfC8sshmnP7OZAXTtbgJHMYxfGExtxZBhnxgnmh7q66SiMvbZCrx04YIzSfSQlEyTmSiekBcZCwCHqBZAJCKQZAy2xHG8f0ZA',
    'FACEBOOK_TOKEN_CDHH': 'EAAFTMCSH9fYBABZAd5wgNypgC4mZAZAkMfxHfptY4eW7zDZBSPMqFOYxEQo8jU6nPxWmZB9iQmDZCkmmZC45TsmjUuQRyYEoPqXbcyh2pkUeox4gkRfH6aoFAAoZCEiZAdRZA4YdZCnLkcJjlT0Dw8DnklS2WZAEmuEGMcs1usNG6GTFP0OJeGbECaoz',
    'FACEBOOK_TOKEN_CBTEST': 'EAANexv7TpxcBAATWSX74MzhNlYXzM0CSDAVPZCrroDJGq3Ortg0dZBxU1T6jmmVLZBVZABJeh95hSzC4ZBwXQDEQVkJtcmXZAZBNihV87FQgSZC2iuAJXJ9eUmBszNM4Fl4CnxkhK5n8Cc4iuYvDWHuZAHJISE3X3WUnfpMbx5ZA6yLQZDZD',
    'FACEBOOK_TOKEN_SAOSTAR': '',

    'VERIFY_TOKEN': 'phuc123',
    'SERVER_URL': 'https://yourdomain'
}
